routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


Route::view('/', 'master')->name('main');
Route::get('/booklist', [PagesController::class, 'booklist'])->name('booklist');

Route::group(['middleware' => ['role:admin'], ['as' => '.']], function () {
    Route::resource('category', CategoryController::class)->middleware("permission:category managment");
    Route::resource('user',     UserController::class)->middleware("permission:user managment");
});

Route::group(['middleware' => ['role:admin|editor'], ['as' => '.']], function () {
    Route::resource('book', BookController::class)->middleware("permission:book managment");
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mt-5">
        @can("user managment")
        <div class="col-md-4">
            <div class="card p-5 text-center">
                 <a href="{{route('user.index')}}">Users</a> 
            </div>
        </div>
        @endcan
        @can("category managment")
        <div class="col-md-4">
            <div class="card p-5 text-center">
                 <a href="{{route('category.index')}}">Categories</a> 
            </div>
        </div>
        @endcan
        @can("book managment")
        <div class="col-md-4">
            <div class="card p-5 text-center">
                 <a href="{{route('book.index')}}">My Books</a> 
            </div>
        </div>
        @endcan

    </div>
</div>
@endsection

resources/views/master.blade.php
@extends('layouts.app')
@section("content")


            <div class="container">
                <div class="row justify-content-center">
                    <section class="content">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">Book List</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table id="booklist" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Image</th>
                                            <th>Title</th>
                                            <th>Description</th>
                                            <th>Categories</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>

        
@endsection
@section('js')
<script>
    $(function () {
        $("#booklist").DataTable({
            processing: true,
            aaSorting: [[0, "desc"]],
            ajax: "{{route('booklist')}}",
            columns: [
                { data: "id", name: "book.id" },
                { data: "image", orderable: false, searchable: false, name: "book.image" },
                { data: "title", name: "book.title" },
                { data: "description", name: "book.description" },
                { data: "category", name: "book.category" },
            ],
        });
    });
</script>    
@endsection