routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


Route::view('/', 'master')->name('main');
Route::get('/booklist', [PagesController::class, 'booklist'])->name('booklist');

Route::group(['middleware' => ['role:admin'], ['as' => '.']], function () {
    Route::resource('category', CategoryController::class)->middleware("permission:category managment");
    Route::resource('user',     UserController::class)->middleware("permission:user managment");
});

Route::group(['middleware' => ['role:admin|editor'], ['as' => '.']], function () {
    Route::resource('book', BookController::class)->middleware("permission:book managment");
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\URL;

class Book extends Model
{
    use HasFactory;

    protected $fillable  = [
        'title', 
        'description', 
        'user_id', 
        'image'
    ];

    public function User()
    {
      return $this->belongsTo(User::class);
    }
    public function category()
    {
      return $this->belongsToMany(Category::class);
    }
    public function image()
    {
      return URL::asset($this->image);
    }

}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BookRequest;
use App\Models\Book;
use App\Models\Category;
use App\Models\User;
use App\Traits\BookTrait;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Image;

class BookController extends Controller
{
    use BookTrait;

    public $categories;
    public $imageUrl;

    public function __construct()
    {
        $this->middleware('auth');

        $this->categories = Category::where('status', 1)->get();
    }

    public function uploadImage($file, $book=null)
    {
        if ($file) {
            
            $filename = Str::random(5).'-'. time().'-'.Str::random(5).'.'. $file->getClientOriginalExtension();
            
            $image = Image::make($file);
            
            Storage::disk('local')->put("private/books/{$filename}", (string) $image->encode());
            
            $this->imageUrl = "storage/private/books/{$filename}";

            self::destroyImage($book);            
        }
    }
    public static function destroyImage($book)
    {
        return ($book)? Storage::disk('local')->delete("private/books/". basename($book->image())) : null;
    }
    
    public function list()
    {
        $user = Auth::user();

        $books = ($user->hasRole("admin"))? Book::all() : auth()->user()->Book;

        return $this->DatatablesList($books);
    }

    public function index()
    {       
        return view('book.index');
    }

    public function create()
    {
        return view('book.create', ["categories"=>$this->categories]);
    }

    public function store(BookRequest $request)
    {
        self::uploadImage($request->image);

        $book = Book::create(["title"=>$request->title, 
                              "description"=>$request->description,
                              "image"=>$this->imageUrl,
                              "user_id"=>auth()->user()->id
                        ]);

        $book->category()->sync($request->category_id, false);

        return redirect()->route('book.index')->with("success", 'Create Successfuly');
    }

    public function edit(Book $book)
    {
        $this->authorize('edit', $book);

        return view('book.update', ["book"=>$book, "categories"=>$this->categories]);
    }

    public function update(BookRequest $request, Book $book)
    {
        $this->authorize('update', $book);

        $this->imageUrl = $book->image;

        self::uploadImage($request->image, $book);

        $book->update(["title"=>$request->title, 
                       "description"=>$request->description,
                       "image"=>$this->imageUrl
                    ]);
                    
        $book->category()->sync($request->category_id);

        return redirect()->route('book.edit', $book->id)->with("success", 'Update Successfuly');
    }

    public function destroy(Book $book)
    {
        $this->authorize('destroy', $book);

        self::destroyImage($book);

        $book->delete();

        return redirect()->route('book.index')->with("success", 'Deleted Successfuly');
    }
}

resources/views/book/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{route('book.index')}}">Books</a></li>
      </ol>
   </nav>

   <div class="row justify-content-center">
      <div class="col-md-12">
         @include('layouts.messages')
         <div class="card">
            <div class="card-header">Add New Book</div>
            <div class="card-body">
               <form action="{{route('book.store')}}" method="post" enctype="multipart/form-data">
                  @csrf                       
                  <div class="form-group">
                     <label for="title"><b>Title</b></label>
                     <input value="{{old('title')}}" id="title" required type="text" class="form-control" name="title" >
                  </div>
                  <div class="form-group">
                     <label for="description"><b>Description</b></label>
                     <textarea id="description" required class="form-control" name="description">{{old('description')}}</textarea>
                  </div>
                  <div class="form-group">
                     <label for=""><b>Categories</b></label>
                     <select required name="category_id[]" class="form-control" multiple>
                        <option disabled selected>Choose Category</option>

                        @foreach($categories as $category)
                        <option value="{{$category->id}}" @if(old('category_id') && in_array($category->id, old('category_id')))) selected @endif>{{$category->name}}</option>
                        @endforeach
                     </select>
                  </div>
                  <div class="form-group">
                     <label for="image"><b>Cover Image</b></label>
                     <input id="image" type="file" class="form-control" name="image" >
                  </div>

                  <div class="mt-3 form-group">                                
                     <button type="submit" class="btn btn-default btn-outline-secondary">Send</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/book/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
      </ol>
   </nav>


   <div class="row justify-content-center">
      <section class="content">
         @include('layouts.messages')
         <div class="box">
            <div class="box-header mb-2">
               <a href="{{route('book.create')}}" class="btn btn-secondary pull-right">Add Book</a>
               <h3 class="box-title">Books List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               <table id="booklist" class="table table-bordered table-striped">
                  <thead>
                      <tr>
                          <th>Id</th>
                          <th>Image</th>
                          <th>Title</th>
                          <th>Description</th>
                          <th>Categories</th>
                          <th>Publisher</th>
                          <th>Action</th>
                      </tr>
                  </thead>
              </table>
            </div>
         </div>
      </section>
   </div>
</div>
@endsection
@section('js')
<script>
    $(function () {
        $("#booklist").DataTable({
            processing: true,
            aaSorting: [[0, "desc"]],
            ajax: "{{route('userBooksList')}}",
            columns: [
               { data: "id", name: "book.id" },
               { data: "image", orderable: false, searchable: false, name: "book.image" },
               { data: "title", name: "book.title" },
               { data: "description", name: "book.description" },
               { data: "category", name: "book.category" },
               { data: "publisher", name: "book.publisher" },
               { data: "action", orderable: false, searchable: false },
            ],
        });
    });
</script>    
@endsection

resources/views/book/update.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{route('book.index')}}">Books</a></li>
      </ol>
   </nav>
   <div class="row justify-content-center">
      <div class="col-md-12">
         @include('layouts.messages')
         <div class="card">
            <div class="card-header">Update Book</div>
            <div class="card-body">
               <form action="{{route('book.update', $book->id)}}" method="post" enctype="multipart/form-data">
                  @csrf        
                  @method('PUT')               
                  <div class="form-group">
                     <label for="title"><b>Title</b></label>
                     <input value="{{$book->title}}" id="title" required type="text" class="form-control" name="title" >
                  </div>
                  <div class="form-group">
                     <label for="description"><b>Description</b></label>
                     <textarea id="description" required class="form-control" name="description">{{$book->description}}</textarea>
                  </div>
                  <div class="form-group">
                     <label for=""><b>Categories</b></label>
                     <select required name="category_id[]" class="form-control" multiple>
                        @foreach($categories as $category)
                        <option value="{{$category->id}}"  @if(in_array($category->id, $book->category->pluck('id')->toArray()))) selected @endif>{{$category->name}}</option>
                        @endforeach
                     </select>
                  </div>
                  <div class="form-group">
                     <label for="image"><b>Cover Image</b></label>
                     @if($book->image) <img src="{{$book->image()}}" width="150" class="d-block mt-1 mb-1"> @endif
                     <input id="image" type="file" class="form-control" name="image">
                  </div>

                  <div class="mt-3 form-group">                                
                     <button type="submit" class="btn btn-default btn-outline-secondary">Send</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection