routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


Route::view('/', 'master')->name('main');
Route::get('/booklist', [PagesController::class, 'booklist'])->name('booklist');

Route::group(['middleware' => ['role:admin'], ['as' => '.']], function () {
    Route::resource('category', CategoryController::class)->middleware("permission:category managment");
    Route::resource('user',     UserController::class)->middleware("permission:user managment");
});

Route::group(['middleware' => ['role:admin|editor'], ['as' => '.']], function () {
    Route::resource('book', BookController::class)->middleware("permission:book managment");
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable  = [
        'name', 
        'status'
    ];

    public function books()
    {
      return $this->belongsToMany(Book::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use DataTables;

class CategoryController extends Controller
{

    public function index()
    {
        return view('category.index');
    }
    public function list()
    {
        $results = Category::all();

        return Datatables::of($results)
                        ->editColumn('status', function ($result) {                
                            return ($result->status==1)? "Active" : "Disabled";
                        })
                        ->addColumn('action', function($result){
                            $update = route("category.edit", $result->id);
                            $destroy = route("category.destroy", $result->id);

                            return view('partials.datatables.action', compact("update", 'destroy'));
                        })
                        ->rawColumns(["action"])
                        ->make(true);

    }

    public function create()
    {
        return view('category.create');
    }

    public function store(CategoryRequest $request)
    {
        Category::create(['name'=>$request->name, "status"=>$request->status]);

        return redirect()->route('category.index')->with("success", 'Create Successfuly');
    }

    public function edit(Category $category)
    {
        return view('category.update', compact("category"));
    }

    public function update(CategoryRequest $request, Category $category)
    {
        $category->update(['name'=>$request->name, "status"=>$request->status]);

        return redirect()->route('category.edit', $category->id)->with("success", 'Update Successfuly');
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('category.index')->with("success", 'Deleted Successfuly');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{route('category.index')}}">Categories</a></li>
      </ol>
   </nav>

   <div class="row justify-content-center">
      <div class="col-md-12">
         @include('layouts.messages')
         <div class="card">
            <div class="card-header">Add New Category</div>
            <div class="card-body">
               <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data">
                  @csrf                       
                  <div class="form-group">
                     <label for=""><b>Name</b></label>
                     <input value="{{old('name')}}" required type="text" class="form-control" name="name">
                  </div>

                  <div class="form-check">
                     <input class="form-check-input"  value="1" type="radio" name="status" id="flexRadioDefault1" checked>
                     <label class="form-check-label" for="flexRadioDefault1">Active</label>
                   </div>
                   <div class="form-check">
                     <input class="form-check-input" value="0" type="radio" name="status" id="flexRadioDefault2">
                     <label class="form-check-label" for="flexRadioDefault2">Disabled</label>
                   </div>
                   
                  <div class="mt-3 form-group">                                
                     <button type="submit" class="btn btn-default btn-outline-secondary">Send</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
      </ol>
   </nav>


   <div class="row justify-content-center">
      <section class="content">
         @include('layouts.messages')
         <div class="box">
            <div class="box-header mb-2">
               <a href="{{route('category.create')}}" class="btn btn-secondary pull-right">Add Category</a>
               <h3 class="box-title">Categories List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               <table id="booklist" class="table table-bordered table-striped">
                  <thead>
                     <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Action</th>
                     </tr>
                  </thead>
               </table>
            </div>
         </div>
      </section>
   </div>
</div>
@endsection
@section('js')
<script>
   $(function () {
       $("#booklist").DataTable({
           processing: true,
           aaSorting: [[0, "desc"]],
           ajax: "{{route('categorylist')}}",
           columns: [
               { data: "name", name: "category.name" },
               { data: "status", name: "category.status" },
               { data: "action", orderable: false, searchable: false },
           ],
       });
   });
</script>    
@endsection

resources/views/category/update.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{route('category.index')}}">Categories</a></li>
      </ol>
   </nav>
   <div class="row justify-content-center">
      <div class="col-md-12">
         @include('layouts.messages')
         <div class="card">
            <div class="card-header">Update Category</div>
            <div class="card-body">
               <form action="{{route('category.update', $category->id)}}" method="post" enctype="multipart/form-data">
                  @csrf        
                  @method('PUT')               
                  <div class="form-group">
                     <label for=""><b>Name</b></label>
                     <input value="{{$category->name}}" type="text" class="form-control" name="name" required>
                  </div>
                  
                  <div class="form-check">
                     <input class="form-check-input"  value="1" type="radio" name="status" id="flexRadioDefault1" @if($category->status==1) checked @endif>
                     <label class="form-check-label" for="flexRadioDefault1">Active</label>
                   </div>
                   <div class="form-check">
                     <input class="form-check-input" value="0" type="radio" name="status" id="flexRadioDefault2" @if($category->status==0) checked @endif>
                     <label class="form-check-label" for="flexRadioDefault2">Disabled</label>
                   </div>

                  <div class="mt-3 form-group">                                
                     <button type="submit" class="btn btn-default btn-outline-secondary">Send</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection