routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


Route::view('/', 'master')->name('main');
Route::get('/booklist', [PagesController::class, 'booklist'])->name('booklist');

Route::group(['middleware' => ['role:admin'], ['as' => '.']], function () {
    Route::resource('category', CategoryController::class)->middleware("permission:category managment");
    Route::resource('user',     UserController::class)->middleware("permission:user managment");
});

Route::group(['middleware' => ['role:admin|editor'], ['as' => '.']], function () {
    Route::resource('book', BookController::class)->middleware("permission:book managment");
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function Book()
    {
      return $this->hasMany(Book::class);
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\UserStoreRequest;
use App\Http\Requests\User\UserUpdateRequest;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use DataTables;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    public $roles;

    public function __construct()
    {
        $this->roles = Role::all();
    }
    public function index()
    {
        return view('user.index');
    }

    public function list()
    {
        $results = User::all();

        return Datatables::of($results)            
                        ->addColumn('action', function($result){
                            $update = route("user.edit", $result->id);
                            $destroy = route("user.destroy", $result->id);

                            return view('partials.datatables.action', compact("update", 'destroy'));
                        })
                        ->editColumn('created_at', function ($result) {
                            return $result->created_at->format('d/m/Y H:i');
                        })
                        ->addColumn('role', function($user){
                            $results = $user->roles;

                            return view('partials.datatables.list', compact("results"));
                        })
                        ->rawColumns(["role", "action"])
                        ->make(true);
    }

    public function create()
    {
        return view('user.create', ["roles"=>$this->roles]);
    }

    public function store(UserStoreRequest $request)
    {
        $role = Role::where("name", $request->role)->first();  
        
        $user = User::create([
            "name"=>$request->name, 
            "email"=>$request->email, 
            "password"=> Hash::make($request->password) 
        ]);

        $user->syncRoles($request->role);
        $user->syncPermissions($role->permissions);            

        return redirect()->route('user.index')->with("success", 'Create Successfuly');
    }

    public function edit(User $user)
    {
        return view('user.update', ["roles"=>$this->roles, "user"=>$user]);
    }

    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update([
            "name" => $request->name, 
            "email" => $request->email, 
            "password"=> ($request->password)? Hash::make($request->password) : $user->password, 
        ]);

        $user->roles()->detach();
        $user->permissions()->detach();

        $role = Role::where("name", $request->role)->first();
 
        $user->assignRole($request->role);
        $user->syncPermissions($role->permissions);            

        return redirect()->route('user.edit', $user->id)->with("success", 'Update Successfuly');
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('user.index')->with("success", 'Deleted Successfuly');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{route('user.index')}}">Users</a></li>
      </ol>
   </nav>

   <div class="row justify-content-center">
      <div class="col-md-12">
         @include('layouts.messages')
         <div class="card">
            <div class="card-header">Add New User</div>
            <div class="card-body">
               <form action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
                  @csrf                       
                  <div class="form-group">
                     <label for="name"><b>Name</b></label>
                     <input value="{{old('name')}}" id="name" required type="text" class="form-control" name="name" >
                  </div>
                  <div class="form-group">
                     <label for="email"><b>Email</b></label>
                     <input value="{{old('email')}}" id="email" required type="email" class="form-control" name="email" >
                  </div>
                  <div class="form-group">
                     <label for="password"><b>Password</b></label>
                     <input id="passwod" required type="password" class="form-control" name="password" >
                  </div>
                  <div class="form-group">
                     <label for="password_confirmation"><b>Password Confirmation:</b></label>
                     <input id="password_confirmation" required type="password" class="form-control" name="password_confirmation" >
                  </div>

                  <div class="form-group">
                     <label for=""><b>Role</b></label>
                     <select required name="role[]" class="form-control" multiple>
                        <option disabled selected>Choose Role</option>

                        @foreach($roles as $role)
                        <option value="{{$role->name}}" @if(old('role') && in_array($role->name, old('role')))) selected @endif>{{$role->name}}</option>
                        @endforeach
                     </select>
                  </div>


                  <div class="mt-3 form-group">                                
                     <button type="submit" class="btn btn-default btn-outline-secondary">Send</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
      </ol>
   </nav>


   <div class="row justify-content-center">
      <section class="content">
         @include('layouts.messages')
         <div class="box">
            <div class="box-header mb-2">
               <a href="{{route('user.create')}}" class="btn btn-secondary pull-right">Add User</a>
               <h3 class="box-title">Users List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               <table id="booklist" class="table table-bordered table-striped">
                  <thead>
                     <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Created At</th>
                        <th>Roles</th>
                        <th>Action</th>
                     </tr>
                  </thead>
               </table>
            </div>
         </div>
      </section>
   </div>
</div>
@endsection
@section('js')
<script>
   $(function () {
       $("#booklist").DataTable({
           processing: true,
           aaSorting: [[0, "desc"]],
           ajax: "{{route('userlist')}}",
           columns: [
               { data: "name", name: "user.name" },
               { data: "email", name: "user.email" },
               { data: "created_at", name: "user.created_at" },
               { data: "role", name: "user.role" },
               { data: "action", orderable: false, searchable: false },
           ],
       });
   });
</script>    
@endsection

resources/views/user/update.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{route('main')}}">Home</a></li>
         <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{route('user.index')}}">Users</a></li>
      </ol>
   </nav>
   <div class="row justify-content-center">
      <div class="col-md-12">
         @include('layouts.messages')
         <div class="card">
            <div class="card-header">Update User</div>
            <div class="card-body">
               <form action="{{route('user.update', $user->id)}}" method="post" enctype="multipart/form-data">
                  @csrf        
                  @method('PUT')               
                  <div class="form-group">
                     <label for="name"><b>Name</b></label>
                     <input id="name" value="{{$user->name}}" required type="text" class="form-control" name="name" >
                  </div>
                  <div class="form-group">
                     <label for="email"><b>Email</b></label>
                     <input id="email" value="{{$user->email}}" required type="email" class="form-control" name="email" >
                  </div>
                  <div class="form-group">
                     <label for="password"><b>Password</b></label>
                     <input type="password" class="form-control" name="password" >
                  </div>
                  <div class="form-group">
                     <label for="password"><b>Password Confirmation</b></label>
                     <input type="password" class="form-control" name="password_confirmation" >
                  </div>
                  <div class="form-group">
                     <label for=""><b>Role</b></label>
                     <select required name="role[]" class="form-control" multiple>

                        @foreach($roles as $role)
                        <option value="{{$role->name}}" @if(in_array($role->id, $user->roles->pluck('id')->toArray()))) selected @endif>{{$role->name}}</option>

                        @endforeach
                     </select>
                  </div>

                  <div class="mt-3 form-group">                                
                     <button type="submit" class="btn btn-default btn-outline-secondary">Send</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection